learning_log/learning_log/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^users/', include(('users.urls', 'users'), namespace='users')),
    url('', include(('learning_logs.urls', 'learning_logs'), namespace='learning_logs')),
]

learning_log/learning_logs/urls.py
"""Defines URL patterns for learning_logs."""
from django.conf.urls import url

from . import views
urlpatterns = [
    # Home page
    url(r'^$', views.index, name='index'),
    # Show all topics.
    url(r'^topics/$', views.topics, name='topics'),
    # Show about the website
    url(r'about', views.about, name='about'),
    # Detail page for a single topic
    url(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),
    # Page for adding a new topic
    url(r'^new_topic/$', views.new_topic, name='new_topic'),
    # Page for adding a new entry
    url(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),
    # Page for editing an entry
    url(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry,
    name='edit_entry'),
]

learning_log/users/urls.py
"""Defines URL patterns for users"""
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LoginView
from . import views



urlpatterns = [
    # Login page
    url(r'^login/$', LoginView.as_view(),{'registration/login.html': 'users/login.html'}, name='login'),
    # Logout page
    url(r'^logout/$', views.logout_view, name='logout'),
    # Registration page
    url(r'^register/$', views.register, name='register'), 
]

learning_log/dashboard/models.py
from django.db import models

# Create your models here.

learning_log/learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

class Topic(models.Model):
    """A topic the user is learning about"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, )
    def __str__(self):
        """Return a string representation of the model."""
        return self.text
    
def __str__(self):
    """Return a string representation of the model."""
    return self.title + " / " + self.author + " / " + self.read

class Entry(models.Model):
    """Something specific learned about a topic"""
    topic = models.ForeignKey('Topic', on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'
    def __str__(self):
        """Return a string representation of the model."""
        return self.text[:50] + "..."

learning_log/users/models.py
from django.db import models

# Create your models here.

learning_log/learning_logs/forms.py
from django import forms

from .models import Topic

from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}
class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_log/dashboard/views.py
from django.shortcuts import render

# Create your views here.

learning_log/learning_logs/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .models import Topic, Entry
from .forms import TopicForm, EntryForm

# LIST OF VIEWS
def index(request):
    """The home page for Learning Log"""
    return render(request, 'learning_logs/index.html')

@login_required
def topics(request):
    """Show all topics."""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    topics = Topic.objects.order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)

@login_required
def topic(request, topic_id):
    """Show a single topic and all its entries."""
    topic = Topic.objects.get(id=topic_id)
    topic = get_object_or_404(Topic, id=topic_id)
    # Make sure the topic belongs to the current user.
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)

@login_required
def new_topic(request):
    """Add a new topic."""
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = TopicForm()
    else:
        # POST data submitted; process data.
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))
    
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    """Add a new entry for a particular topic."""
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = EntryForm()
    else:
        # POST data submitted; process data.
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic',args=[topic_id]))

    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    """Edit an existing entry."""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        # Initial request; pre-fill form with the current entry.
        form = EntryForm(instance=entry)
    else:
        # POST data submitted; process data.
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic',args=[topic.id]))

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)

@login_required
def about(request):
    return render(request, 'learning_logs/about.html')

learning_log/users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm


def logout_view(request):
    """Log the user out."""
    logout(request)
    return HttpResponseRedirect(reverse('learning_logs:index'))

def register(request):
    """Register a new user."""
    if request.method != 'POST':
        # Display blank registration form.
        form = UserCreationForm()
    else:
        # Process completed form.
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Log the user in and then redirect to home page.
            authenticated_user = authenticate(username=new_user.username,password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('learning_logs:index'))
    context = {'form': form}
    return render(request, 'registration/register.html', context)

learning_log/learning_logs/templates/learning_logs/about.html
{% extends "learning_logs/base.html" %}
{% block header %}
<div class='jumbotron'>ABOUT ME</div>
<div class="card-container">
    
	<img class="round" src="https://i.imgur.com/HYrK4rW.png" alt="user" />
	<h3>Neale Oliva</h3>
	<p><center>CPE2A</center></p>
	<p><center>Designer and Software Developer</center></p>
	<div class="skills">
		<div class='oliva2'>SKILLS</h1></div>
		<ul>
			<li>HTML</li>
			<li>CSS</li>
			<li>JavaScript</li>
            <li>Python</li>
            <li>Django</li>
		</ul>
	</div>
</div>

<footer>
</footer>
<style>
    .card-container {
        background-color: #00000094;
        border-radius: 5px;
        box-shadow: 0px 10px 20px -10px rgb(0 0 0 / 75%);
        color: #B3B8CD;
        padding-top: 30px;
        position: relative;
        margin-right: auto;
        margin-left: auto;
        width: 350px;
        max-width: 100%;
        text-align: center;
    }

.card-container .pro {
	color: #231E39;
	background-color: #FEBB0B;
	border-radius: 3px;
	font-size: 14px;
	font-weight: bold;
	padding: 3px 7px;
	position: absolute;
	top: 30px;
	left: 30px;
}

.card-container .round {
	border: 1px solid #03BFCB;
	border-radius: 50%;
	padding: 7px;
}

button.primary {
	background-color: #03BFCB;
	border: 1px solid #03BFCB;
	border-radius: 3px;
	color: #231E39;
	font-family: Montserrat, sans-serif;
	font-weight: 500;
	padding: 10px 25px;
}

button.primary.ghost {
    background-color: #03BFCB;
    border: 1px solid #03BFCB;
    border-radius: 3px;
    color: #231E39;
    font-family: Montserrat, sans-serif;
    font-weight: 500;
    padding: 10px 25px;
}

.skills {
    background-color: #00000094;
    text-align: left;
    padding: 15px;
    margin-top: 30px;
}

.skills ul {
    list-style-type: none;
    margin: 0;
    padding-left: 9px;
}

.skills ul li {
	border: 1px solid #2D2747;
	border-radius: 2px;
	display: inline-block;
	font-size: 12px;
	margin: 0 7px 7px 0;
	padding: 7px;
}

footer {
    background-color: #222;
    color: #fff;
    font-size: 14px;
    bottom: 0;
    position: fixed;
    left: 0;
    right: 0;
    text-align: center;
    z-index: 999;
}

footer p {
    margin: 10px 0;
}

footer i {
    color: red;
}

footer a {
    color: #3c97bf;
    text-decoration: none;
}
</style>
{% endblock header %}
{% block content %}

{% endblock content %}

learning_log/learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}
{% block content %}
 <p><a href="{% url 'learning_logs:topic' topic.id %}"><h6>{{ topic }}</h6></a></p>

 <div class='pz'>Editing the Entry</div>

<form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post'>
 {% csrf_token %}
 {{ form.as_p }}
 <div class="h9"><button name="submit">Save Changes</button></div>
 </form>
{% endblock content %}

learning_log/learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}
{% block header %}
<div class='jumbotron'>
 <h1>TRACK YOUR LEARNING</h1>
 </div>
{% endblock header %}
{% block content %}
<div class='h15'>
    <a href="{% url 'users:register' %}">Register an account</a> to make
    your own Learning Log, and list the topics you're learning about.
    <br>
    <br>
    Whenever you learn something new about a topic, make an entry
    summarizing what you've learned.
</div>
{% endblock content %}

learning_log/learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}
{% block content %}
<p><a href="{% url 'learning_logs:topic' topic.id %}"><h6>{{ topic }}</h6></a></p>

<form action="{% url 'learning_logs:new_entry' topic.id %}" method='post'>
 {% csrf_token %}
 {{ form.as_p }}
 <div class="h9"><button name='submit'><h9>Add Entry</button></div>
 </form>

{% endblock content %}

learning_log/learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}
{% block header %}
 <h6>New Topic</h6>
{% endblock header %}
{% block content %}

<form action="{% url 'learning_logs:new_topic' %}" method='post'
 class="form">

 {% csrf_token %}
{% bootstrap_form form %}

{% buttons %}
 <div class="h9"><button name="submit">Create</button></div>
 {% endbuttons %}

 </form>

{% endblock content %}

learning_log/learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}
 {% block header %}
 <h6>{{ topic }}</h6>
{% endblock header %}
{% block content %}
 <p>
 <h5><a href="{% url 'learning_logs:new_entry' topic.id %}">New Entry</a></h5>
 </p>
 {% for entry in entries %}
 <div class="panel panel-default">
 <div class="panel-heading">
<h6>
 {{ entry.date_added|date:'M d, Y H:i' }}
<small>
 <a href="{% url 'learning_logs:edit_entry' entry.id %}">
 <h8>EDIT</h8></a>
 </small>
 </h6>
 </div>
<div class="panel-body">
 {{ entry.text|linebreaks }}
 </div>
 </div> <!-- panel -->
 {% empty %}

   <p>There are no entries for this topic yet.</p>

 {% endfor %}
 
{% endblock content %}

learning_log/learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}
{% block header %}
<div class='jumbotron'>Topics</div>
{% endblock header %}
{% block content %}
<div class='olivag'><a href="{% url 'learning_logs:new_topic' %}">New Topic</h5></div>
    {% for topic in topics %}
    

        <div class='h14'>
            <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
        </div>
    
     {% empty %}
        <li>No topics have been added yet.</li>
    {% endfor %}

      
    
{% endblock content %}